//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouFinancialHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure_Base
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expenditure_Base()
        {
            this.Expenditure_Objective = new HashSet<Expenditure_Objective>();
            this.Movements = new HashSet<Movement>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public double Value { get; set; }
        public int FK_Category { get; set; }
        public byte status { get; set; }
        public byte E_Relevance { get; set; }
        public int FK_User { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expenditure_Objective> Expenditure_Objective { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movement> Movements { get; set; }
    }
}
