//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouFinancialHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure_Objective
    {
        public int id { get; set; }
        public int FK_Expenditure_Base { get; set; }
        public int Quantity { get; set; }
        public double Subtotal { get; set; }
        public System.DateTime Objective_Date { get; set; }
        public string Annotations { get; set; }
        public byte status { get; set; }
    
        public virtual Expenditure_Base Expenditure_Base { get; set; }
    }
}
