//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouFinancialHelper.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YFHConext : DbContext
    {
        public YFHConext()
            : base("name=YFHConext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Expenditure_Base> Expenditure_Base { get; set; }
        public virtual DbSet<Expenditure_Objective> Expenditure_Objective { get; set; }
        public virtual DbSet<Movement> Movements { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
